// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4zv0Vlr6253_joYHsrQEsjsJFnN9lIg',
    appId: '1:802183520437:web:70e2a15ca13b00ced7defc',
    messagingSenderId: '802183520437',
    projectId: 'my-project-66697',
    authDomain: 'my-project-66697.firebaseapp.com',
    databaseURL: 'https://my-project-66697-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-66697.appspot.com',
    measurementId: 'G-BFE5KMWCGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDe2sWvTX2tRJCVYQ-xm7tA0HTmsibd4',
    appId: '1:802183520437:android:72829667df48038bd7defc',
    messagingSenderId: '802183520437',
    projectId: 'my-project-66697',
    databaseURL: 'https://my-project-66697-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-66697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpvmakMnEag9hEb1aBCp8CKzFQ1QBr9Q',
    appId: '1:802183520437:ios:eaf8d22c93f661ffd7defc',
    messagingSenderId: '802183520437',
    projectId: 'my-project-66697',
    databaseURL: 'https://my-project-66697-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-66697.appspot.com',
    iosClientId: '802183520437-s2jtc4qjb16bbnuloar2cpmktg8m1c10.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
